auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: NeedDo.com
url: http://needdo.com
feed: /atom.xml
author_info: <a href="http://needdo.com/">Needdo</a>

comments:
provider : disqus
disqus :
short_name : hanchentech
